In [1]:
import numpy as np
import pandas as pd
from collections import Counter

from rdflib import Graph, Literal, RDF, RDFS, URIRef, Namespace, BNode
from rdflib.namespace import SDO, XSD, PROV
import re
from tqdm import tqdm

In [2]:

g = Graph()
products_ns = Namespace('http://products-kg.org/')
products_scheme = Namespace('http://products-kg.org/scheme/')

g.bind("schema", SDO)
g.bind("rdf", RDF)
g.bind("rdfs", RDFS)
g.bind("xsd", XSD)
g.bind("prov", PROV)
g.bind("pkg", products_ns)
g.bind("pkgs", products_scheme)

# Explicitly define classes that are used in the graph
g.add((SDO.Product, RDF.type, RDFS.Class))
g.add((SDO.Offer, RDF.type, RDFS.Class))
g.add((SDO.PropertyValue, RDF.type, RDFS.Class))
g.add((SDO.AggregateRating, RDF.type, RDFS.Class))
g.add((SDO.QuantitativeValue, RDF.type, RDFS.Class))
g.add((PROV.Entity, RDF.type, RDFS.Class))
g.add((SDO["OnlineStore"], RDF.type, RDFS.Class))
g.add((SDO["OnlineStore"], RDFS.comment, Literal("An eCommerce site", lang='en')))

# Basic properties(note that these are not all properties used in the graph, these are only required properties. More other properties could be used during graph enrichment)
g.add((SDO.additionalProperty, RDF.type, RDF.Property))
g.add((SDO.additionalProperty, RDFS.domain, SDO.Product))
g.add((SDO.additionalProperty, RDFS.range, SDO.PropertyValue))

g.add((SDO.name, RDF.type, RDF.Property))
g.add((SDO.name, RDFS.domain, SDO.Product))
g.add((SDO.name, RDFS.range, XSD.string))

g.add((SDO.description, RDF.type, RDF.Property))
g.add((SDO.description, RDFS.domain, SDO.Product))
g.add((SDO.description, RDFS.range, XSD.string))

g.add((SDO.offers, RDF.type, RDF.Property))
g.add((SDO.offers, RDFS.domain, SDO.Product))
g.add((SDO.offers, RDFS.range, SDO.Offer))

g.add((SDO.price, RDF.type, RDF.Property))
g.add((SDO.price, RDFS.domain, SDO.Offer))
g.add((SDO.price, RDFS.range, XSD.float))

g.add((PROV.wasDerivedFrom, RDF.type, RDF.Property))
g.add((PROV.wasDerivedFrom, RDFS.domain, SDO.Product))
g.add((PROV.wasDerivedFrom, RDFS.range, PROV.Entity))

g.add((products_scheme["fromOnlineStore"], RDF.type, RDF.Property))
g.add((products_scheme["fromOnlineStore"], RDFS.domain, SDO.Product))
g.add((products_scheme["fromOnlineStore"], RDFS.range, SDO["OnlineStore"]))
g.add((products_scheme["fromOnlineStore"], RDFS.comment, Literal("An online store in which product can be found", lang='en')))


print(f"Ontology defined. Graph currently has {len(g)} triples.")
print(g.serialize(destination="../data/ontology_graph.ttl", format="ttl"))

Ontology defined. Graph currently has 30 triples.
[a rdfg:Graph;rdflib:storage [a rdflib:Store;rdfs:label 'Memory']].

C:\Users\denve\AppData\Roaming\Python\Python313\site-packages\IPython\core\interactiveshell.py:3701: UserWarning: Code: OnlineStore is not defined in namespace SDO
  exec(code_obj, self.user_global_ns, self.user_ns)

# Enriching with Amazon data

In [3]:
df_amazon = pd.read_pickle("../data/amazon_products_cleaned.pkl")
df_amazon.reset_index(drop=True, inplace=True)
df_amazon.head()

,parent_asin,date_first_available,title,description,main_category,average_rating,rating_number,price,features,details
0,B0BT4CWWC9,2023-01-26,Sunshine On My Shoulders: The Best Of John Den...,"Sunshine On My Shoulders is a 2CD, 36-track co...",Digital Music,4.7,502.0,19.98,NaN,{'Package Dimensions': '5.55 x 4.92 x 0.51 inc...
1,B0BS4L5LP6,2023-01-11,18 Greatest Hits of 38 Special,Track Listings: 1. Rockin' Into The Night 2. H...,Digital Music,5.0,1.0,14.97,NaN,"{'Item Weight': '4 Ounces', 'Run time': '1 hou..."
2,B0BSPBBP89,2023-01-20,The Gift [CD],Second studio album by the multi-million-selli...,Digital Music,4.8,34.0,12.99,NaN,{'Package Dimensions': '5.59 x 4.8 x 0.47 inch...
3,B0BPT1369H,2023-02-14,HIGH DRAMA. CD SIGNED-ADAM LAMBERT,Renowned for re-imagining songs from American ...,Digital Music,4.7,207.0,23.35,NaN,"{'Language': 'English', 'Product Dimensions': ..."
4,B0BVYD326Y,2023-02-15,Hamilton Original Broadway Cast Recording (Exp...,Explicit version. 2015 two CD set. The origina...,Digital Music,4.6,56.0,21.86,NaN,{'Package Dimensions': '5.55 x 4.88 x 0.94 inc...

We are loading Schema.org graph to extract properties that we will dynamically use during graph enrichment

In [4]:
sdo_data = Graph()
sdo_data.parse("https://schema.org/version/latest/schemaorg-all-http.ttl", format="turtle")


# Select all properties that have domain of SDO:Product
results = sdo_data.query("""
PREFIX sdo: <http://schema.org/>

SELECT ?property ?name ?description
WHERE
{

    ?property sdo:domainIncludes sdo:Product.
    ?property rdfs:label ?name.
    ?property rdfs:comment ?description.
}
""")

# We save make name+description for embedding of properties, so that we can search for needed properties as we process the data
sdo_property_index = []
sdo_property_text = []
for result in results:
    sdo_property_index.append({
        "url": result.property,
        "name": result.name,
        "comment": result.description
    })
    # convert property name from camelCase to usual word
    name = re.sub(r'(?<!^)(?=[A-Z])', ' ', result.name)
    sdo_property_text.append(f"{name}")

    # add name and description as separate vectors with the same metadata. So if search doesn't find the match by label it can still
    # find it by description
    sdo_property_index.append({
        "url": result.property,
        "name": result.name,
        "comment": result.description
    })
    sdo_property_text.append(f"{result.description}")

We are creating a vector store from texts extracted `schema.org` graph

In [5]:
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from sentence_transformers import CrossEncoder
from torch import sigmoid

C:\Users\denve\miniconda3\envs\KG_project\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
# embedding_model = HuggingFaceEmbeddings(model_name='BAAI/bge-large-en-v1.5')
embedding_model = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')

# sdo_embeddings = model.encode(sdo_labels)

vector_store = FAISS.from_texts(sdo_property_text, embedding=embedding_model, metadatas=sdo_property_index)

C:\Users\denve\AppData\Local\Temp\ipykernel_620\746124631.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(model_name='sentence-transformers/all-mpnet-base-v2')
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 11884.59it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [7]:
def find_semantic_match(query, vector_store):
    result = vector_store.similarity_search_with_score(query, k=1)[0]

    if result[1] < 0.65:  # distance threshold
        return result[0].metadata
    return None

# re_ranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2', default_activation_function=sigmoid)
#
# def find_semantic_match(query, vector_store) -> dict|None:
#     results = vector_store.similarity_search_with_score(query, k=5)
#
#     pairs = [[query, r[0].page_content] for r in results]
#     scores = re_ranker.predict(pairs)
#
#     # Pair results with their new scores and sort
#     scored_results = sorted(zip(results, scores), key=lambda x: x[1], reverse=True)
#
#
#     best_match, best_score = scored_results[0]
#
#     if best_score > 0.5:
#         return best_match[0].metadata
#     return None

We keep track of all the keys in `details` to later filter our the rare ones

In [8]:
details_key_counter = Counter()
for details in df_amazon['details']:
    if pd.isna(details):
        continue

    for key in details.keys():
        details_key_counter.update([key.lower().strip()])

print(details_key_counter)

Counter({'date first available': 81214, 'manufacturer': 62243, 'item model number': 39703, 'brand': 37174, 'item weight': 36247, 'best sellers rank': 36117, 'department': 33212, 'color': 28875, 'product dimensions': 28321, 'country of origin': 23800, 'material': 22235, 'package dimensions': 20615, 'special feature': 13594, 'style': 12001, 'included components': 8969, 'size': 8944, 'number of items': 8827, 'shape': 8588, 'age range (description)': 6473, 'special features': 6463, 'theme': 6212, 'manufacturer part number': 6044, 'pattern': 5709, 'number of pieces': 5605, 'item dimensions lxwxh': 5509, 'product care instructions': 5452, 'unit count': 5382, 'batteries required?': 4848, 'part number': 4785, 'model name': 4366, '': 3941, 'mounting type': 3897, 'room type': 3810, 'recommended uses for product': 3258, 'batteries included?': 3190, 'finish type': 3162, 'form factor': 3159, 'occasion': 3074, 'brand name': 2885, 'other display features': 2754, 'compatible devices': 2655, 'model': 2621, 'is discontinued by manufacturer': 2544, 'package weight': 2468, 'power source': 2431, 'compatible phone models': 2281, 'item package quantity': 2242, 'whats in the box': 2201, 'item package dimensions l x w x h': 2162, 'specific uses for product': 2161, 'connectivity technology': 1926, 'closure type': 1848, 'item form': 1688, 'material type': 1641, 'suggested users': 1569, 'batteries': 1532, 'capacity': 1526, 'seasons': 1517, 'assembly required': 1509, 'fabric type': 1436, 'warranty description': 1396, 'is dishwasher safe': 1311, 'vehicle service type': 1304, 'indoor/outdoor usage': 1303, 'cartoon character': 1198, 'voltage': 1176, 'label': 1169, 'number of discs': 1164, 'reusability': 1132, 'frame material': 1122, 'original release date': 1092, 'installation type': 1061, 'finish': 1035, 'screen size': 986, 'connector type': 981, 'exterior': 963, 'wattage': 896, 'operating system': 891, 'language': 870, 'fit type': 870, 'standing screen display size': 837, 'series': 815, 'ram': 810, 'light source type': 799, 'material feature': 790, 'sport': 788, 'auto part position': 769, 'processor brand': 765, 'handle material': 762, 'operation mode': 750, 'processor': 749, 'hard drive': 749, 'chipset brand': 744, 'card description': 737, 'number of processors': 702, 'package information': 700, 'target audience': 699, 'hardware platform': 686, 'graphics coprocessor': 685, 'computer memory type': 676, 'controller type': 670, 'hard drive interface': 657, 'frame type': 642, 'water resistance level': 641, 'max screen resolution': 626, 'target species': 620, 'ram memory installed size': 616, 'orientation': 606, 'control method': 602, 'scent': 592, 'back material type': 582, 'cpu model': 582, 'surface recommendation': 566, 'maximum weight recommendation': 561, 'sport type': 558, 'furniture finish': 550, 'screen resolution': 549, 'number of sets': 539, 'oem part number': 533, 'exterior finish': 490, 'shade material': 479, 'is stain resistant': 465, 'flavor': 460, 'pile height': 460, 'hard disk size': 436, 'wall art form': 435, 'rug form type': 435, 'position': 431, 'weave type': 425, 'product benefits': 417, 'ink color': 407, 'graphics card description': 390, 'number of usb 3.0 ports': 376, 'memory storage capacity': 372, 'blade material': 364, 'closure': 363, 'is microwaveable': 361, 'shell type': 356, 'base type': 354, 'blanket form': 353, 'input voltage': 351, 'are batteries included': 347, 'number of light sources': 345, 'construction type': 342, 'wireless type': 337, 'fill material': 334, 'top style': 319, 'number of shelves': 312, 'shade color': 309, 'material type free': 308, 'item firmness description': 308, 'light color': 304, 'material stainless steel': 301, 'abpa partslink number': 296, 'outer material': 292, 'collection name': 289, 'neck style': 282, 'usage': 280, 'finish types': 271, 'manufacturer recommended age': 271, 'hand orientation': 267, 'cable type': 266, 'plant or animal product type': 266, 'fabric warmth description': 265, 'switch type': 259, 'units': 257, 'opacity': 251, 'total usb ports': 248, 'flash memory size': 247, 'cover material': 246, 'lamp type': 246, 'color name': 239, 'installation type self-adhesive': 237, 'color temperature': 235, 'point type': 232, 'material glass': 224, 'is framed?': 224, 'item hardness': 223, 'sheet size': 219, 'switch installation type': 218, 'screen surface description': 218, 'weight limit': 217, 'graphics card ram size': 217, 'release date': 214, 'number of compartments': 211, 'item length': 209, 'pre-printed': 209, 'paint type': 206, 'breed recommendation': 203, 'display type': 201, 'use for': 201, 'hardware interface': 200, 'pricing': 200, 'number of batteries': 197, 'number of usb 2.0 ports': 196, 'connectivity technologies': 195, 'bulb base': 195, 'light fixture form': 194, 'lens color': 191, 'dosage form': 187, 'towel form type': 186, 'model info': 185, 'memory speed': 184, 'optical drive type': 184, 'specification met': 183, 'base material': 183, 'assembled width': 182, 'assembled height': 181, 'assembled length': 181, 'table design': 177, 'shape rectangular': 174, 'back style': 174, 'item volume': 172, 'arm style': 171, 'brightness': 167, 'connector gender': 165, 'fastener type': 164, 'embellishment': 163, 'grip type': 163, 'sheet count': 163, 'battery cell composition': 163, 'light type': 162, 'type of bulb': 160, 'league': 160, 'sleeve type': 159, 'model year': 153, 'type of item': 153, 'wireless communication technology': 151, 'hard drive rotational speed': 151, 'item thickness': 149, 'top material type': 145, 'seat height': 144, 'material plastic': 143, 'cpu speed': 143, 'date first listed on amazon': 141, 'developed by': 141, 'version': 141, 'minimum operating system': 141, 'approximate download time': 141, 'number of drawers': 140, 'connectivity protocol': 139, 'application permissions': 139, 'light source type led': 137, 'corner style': 136, 'flash memory type': 136, 'handle type': 135, 'year': 132, 'curtain form': 129, 'mirror lens type': 126, 'lock type': 126, 'material ceramic': 126, 'skill level': 124, 'head style': 124, 'metal type': 124, 'is oven safe': 122, 'light direction': 121, 'shelf type': 119, 'number of speeds': 119, 'compatible material': 119, 'average battery life (in hours)': 119, 'material vinyl': 116, 'battery capacity': 115, 'control type': 114, 'door style': 114, 'bulb features': 112, 'opening mechanism': 112, 'seating capacity': 111, 'video capture resolution': 111, 'item diameter': 110, 'with lid': 110, 'warranty type': 106, 'noise level': 105, 'total eaches': 105, 'format': 105, 'os': 105, 'seat material type': 104, 'binding': 104, 'spars code': 103, 'shape round': 102, 'diet type': 102, 'pillow type': 102, 'load capacity': 102, 'paper finish': 102, 'number of hooks': 101, 'thread count': 101, 'inner material': 100, 'lens material': 100, 'operating time': 99, 'bowl material': 97, 'shape irregular': 96, 'cpu manufacturer': 96, 'run time': 95, 'human interface input': 95, 'is customizable': 95, 'average life': 93, 'alarm clock': 93, 'compatible device': 93, 'product name': 93, 'speaker type': 91, 'bulb shape size': 91, 'strap type': 90, 'number of settings': 89, 'line size': 89, 'battery cell type': 88, 'installation method': 86, 'wireless communication technologies': 86, 'resolution': 86, 'lift type': 85, 'lens curvature description': 85, 'upholstery fabric type': 84, 'volume': 83, 'data transfer rate': 82, 'remote control included?': 82, 'specific uses': 81, 'current rating': 81, 'type': 81, 'material wood': 81, 'vehicle service type passenger car': 81, 'wireless network technology': 81, 'amperage': 80, 'frame material metal': 80, 'blade length': 80, 'compatibility options': 79, 'material aluminum': 79, 'ruling': 79, 'number of buttons': 79, 'lighting method': 78, 'horsepower': 77, 'blade edge': 77, 'charging time': 76, 'surface recommendation wall': 75, 'battery life': 73, 'page yield': 73, 'blade shape': 72, 'bottle type': 72, 'coverage': 70, 'international protection rating': 70, 'material metal': 70, 'variety': 70, 'number of doors': 70, 'cable feature': 69, 'incandescent equivalent wattage': 69, 'luminous flux': 69, 'other camera features': 69, 'active ingredients': 68, 'planter form': 67, 'fit type vehicle specific fit': 67, 'color rendering index': 66, 'measurement system': 66, 'plug format': 66, 'rear webcam resolution': 66, 'duration': 65, 'package type': 65, 'servings per container': 64, 'number of keys': 63, 'assembly required yes': 63, 'grip size': 63, 'weight': 62, 'fishing technique': 62, 'shaft material': 61, 'upc': 61, 'cutting diameter': 61, 'keyboard description': 61, 'frame material wood': 60, 'number of pockets': 60, 'thread size': 59, 'assembled diameter': 59, 'runtime': 59, 'battery power rating': 59, 'ear placement': 58, 'maximum compatible wattage': 58, 'number of labels': 58, 'hair type': 58, 'style modern': 57, 'microphone form factor': 56, 'ply rating': 56, 'bulb type': 56, 'primary supplement type': 56, 'rated': 56, 'headphones jack': 55, 'wheel size': 55, 'material engineered wood': 55, 'fuel type': 54, 'number of wheels': 54, 'maximum weight capacity': 54, 'seat depth': 54, 'terminal': 54, 'fastener material': 53, 'special ingredients': 53, 'pencil lead degree (hardness)': 53, 'hard disk description': 53, 'lens type': 52, 'number of blades': 51, 'operating life': 51, 'ruling type': 51, 'printer output': 51, 'printing technology': 51, 'maximum pressure': 50, 'ultraviolet light protection': 50, 'age range description': 50, 'battery description': 50, 'filter type': 50, 'maximum range': 50, 'electric fan design': 49, 'bike type': 49, 'media type': 49, 'scanner resolution': 49, 'thread type': 48, 'antenna': 48, 'team name': 47, 'material acrylic': 47, 'number of channels': 46, 'output voltage': 46, 'frequency': 46, 'is electric': 45, 'watch movement': 45, 'max number of supported devices': 45, 'operating voltage': 44, 'grit type': 44, 'cellular technology': 44, 'write speed': 44, 'maximum rotational speed': 43, 'tv size': 43, 'material leather': 43, 'number of panels': 43, 'fit type direct replacement': 43, 'number of ports': 43, 'drive system': 43, 'wireless carrier': 43, 'refresh rate': 43, 'liquid volume': 42, 'access location': 42, 'pages': 42, 'number of handles': 42, 'display resolution maximum': 42, 'has nonstick coating': 41, 'number of doors 2': 41, 'cooling method': 41, 'cap type': 40, 'switch style': 39, 'allergen information': 39, 'product grade': 39, 'container material': 39, 'fixture type': 39, 'material paper': 39, 'mirror adjustment': 39, 'shape square': 38, 'mounting type tabletop mount': 38, 'fit type universal fit': 38, 'configuration': 38, 'glove type': 38, 'sound level': 38, 'wireless communication standard': 38, 'supported internet services': 38, 'body material': 37, 'number of strings': 37, 'caster type': 37, 'certification': 37, 'surface recommendation window': 37, 'minimum compatible size': 37, 'wick quantity': 37, 'clarity': 37, 'speed rating': 36, 'controls type': 36, 'deck length': 36, 'display technology': 36, 'frequency band class': 36, 'minimum weight capacity': 35, 'photo sensor technology': 35, 'maximum horsepower': 34, 'actuator type': 34, 'camcorder type': 34, 'back material': 33, 'maximum height': 33, 'skin type': 33, 'number of resistance levels': 33, 'magnification maximum': 33, 'closure material': 33, 'contact type': 33, 'number of jets': 33, 'output wattage': 32, 'inlet connection type': 32, 'animal theme': 32, 'beam angle': 32, 'upper temperature rating': 32, 'speed': 31, 'pocket description': 31, 'coffee maker type': 31, 'video capture format': 31, 'grade rating': 31, 'top material': 30, 'material polyester': 30, 'item display dimensions': 30, 'bristle type': 30, 'neck size': 30, 'maximum speed': 30, 'number of programs': 30, 'deck width': 30, 'auto shutoff': 30, 'leg style': 30, 'floor area': 30, 'material faux leather': 30, 'max input sheet capacity': 30, 'warranty': 30, 'read speed': 30, 'personal computer design type': 30, 'setting type': 30, 'speakers maximum output power': 29, 'head material': 29, 'is waterproof': 29, 'material silicone': 29, 'brake style': 29, 'color family': 29, 'tray type': 29, 'print media': 29, 'paper weight': 29, 'writing instrument form': 29, 'gps': 29, 'insulation material': 28, 'is cordless?': 28, 'null': 28, 'polar pattern': 27, 'platform': 27, 'hard disk form factor': 27, 'net content weight': 26, 'suspension type': 26, 'night vision': 26, 'objective lens diameter': 26, 'assembly instructions': 26, 'material acrylonitrile butadiene styrene (abs)': 26, 'roll quantity': 26, 'vehicle service type car': 26, 'vehicle service type passenger car, truck': 26, 'graphics ram size': 26, 'material acrylonitrile butadiene styrene': 25, 'spout height': 25, 'light path distance': 25, 'thickness': 25, 'output current': 25, 'color rendering index (cri)': 25, 'material composition': 25, 'keyboard backlighting color support': 25, 'digital storage capacity': 25, 'video output interface': 25, 'is foldable': 24, 'pad type': 24, 'wheel type': 24, 'item width': 24, 'impedance': 23, 'rim width': 23, 'construction': 23, 'lid material': 23, 'grit material': 23, 'band material type': 23, 'sensor type': 23, 'shank type': 23, 'tab position': 23, 'compatible fastener range': 23, 'incontinence protector type': 22, 'line weight': 22, 'grit number': 22, 'hanging method': 22, 'light source type halogen': 22, 'map type': 22, 'sterility rating': 22, 'audio jack': 22, 'external testing certification': 21, 'model number': 21, 'section width': 21, 'material alloy steel': 21, 'annual energy consumption': 21, 'noise': 21, 'grip material': 21, 'number of dividers': 21, 'band color': 21, 'lining description': 21, 'mounting type wall mount': 21, 'built-in light': 21, 'material rubber': 21, 'product grade replacement part': 21, 'secure digital association speed class': 21, 'pattern match': 21, 'surface recommendation glass': 20, 'style knobs': 20, 'auto part position front': 20, 'tool flute type': 20, 'shape l-shape': 20, 'contact material': 20, 'real angle of view': 20, 'minimum focal length': 20, 'data link protocol': 20, 'noise control': 20, 'shirt form type': 20, 'aspect ratio': 19, 'maximum power': 19, 'burner type': 19, 'handle/lever placement': 19, 'valve type': 19, 'energy star': 19, 'life vest type': 19, 'number of players': 19, 'focus type': 19, 'seat width': 19, 'material polyvinyl chloride': 19, 'packaging': 19, 'furniture leg material': 19, 'maximum weight recommendation 250 pounds': 19, 'shelf type floating shelf': 19, 'number of lights': 19, 'tuner technology': 19, 'hard disk interface': 19, 'scale length': 18, 'ac adapter current': 18, 'tread type': 18, 'hose length': 18, 'maximum incline percentage': 18, 'surface recommendation nail': 18, 'total power outlets': 18, 'mounting type insert mount': 18, 'graded by': 18, 'movement detection technology': 18, 'max printspeed monochrome': 18, 'base width': 18, 'included security features': 17, 'seat back interior height': 17, 'frame material alloy steel': 17, 'accessory connection type': 17, 'power source corded electric': 17, 'fishing line type': 17, 'shelf type wood': 17, 'coating description': 17, 'is dishwasher safe yes': 17, 'circuit type': 17, 'audio output mode': 17, 'gpu clock speed': 17, 'string material': 16, 'battery type': 16, 'proficiency level': 16, 'instrument': 16, 'air flow capacity': 16, 'tensile strength': 16, 'number of springs': 16, 'frame size': 16, 'head type': 16, 'desk design': 16, 'frame material engineered wood': 16, 'auto part position inside': 16, 'main power connector type': 16, 'switch type push button': 16, 'effective still resolution': 16, 'camera lens description': 16, 'scanner type': 16, 'film format type': 16, 'exposure control type': 16, 'graphics processor manufacturer': 16, 'hole count': 16, 'fretboard material': 15, 'neck material type': 15, 'efficiency': 15, 'nominal wall thickness': 15, 'bulb length': 15, 'belt style': 15, 'seat material type foam': 15, 'occupancy': 15, 'fill material type': 15, 'minimum weight recommendation': 15, 'defrost': 15, 'blade color': 15, 'cooling power': 15, 'alert type': 15, 'number of positions': 15, 'total hdmi ports': 15, 'ram memory technology': 15, 'maximum print speed (color)': 15, 'compatible printer models': 15, 'gauge': 14, 'number of keyboard keys': 14, 'signal format': 14, 'outside diameter': 14, 'light source wattage': 14, 'fabric weight': 14, 'wheel material': 14, 'magnification minimum': 14, 'shelf type tiered shelf': 14, 'input current': 14, 'voice command': 14, 'movement type': 14, 'power connector type': 14, 'rim size': 13, 'maximum flow rate': 13, 'surround sound channel configuration': 13, 'tank volume': 13, 'tread depth': 13, 'golf club flex': 13, 'temperature rating': 13, 'bearing material': 13, 'finderscope': 13, 'stone color': 13, 'material engineered wood, metal': 13, 'seating capacity 2': 13, 'material glass, bamboo': 13, 'display resolution': 13, 'edge style': 13, 'radio bands supported': 13, 'display size': 13, 'photo filter effect type': 13, 'backing': 13, 'audio sensitivity': 12, 'string material type': 12, 'load index': 12, 'refrigerant': 12, 'style compatible': 12, 'capacity total': 12, 'golf club loft': 12, 'chest size': 12, 'tension level': 12, 'bottle count': 12, 'occasion birthday': 12, 'gem type': 12, 'number of doors 1': 12, 'reservoir capacity': 12, 'color code': 12, 'case material': 12, 'magnification strength': 12, 'optical sensor technology': 12, 'dental floss type': 12, 'compatible mountings': 12, 'cpu socket': 12, 'photo filter thread size': 12, 'guitar bridge system': 11, 'fretboard material type': 11, 'maximum voltage': 11, 'shape semicircular': 11, 'mounting type freestanding': 11, 'fastener size': 11, 'frame material plastic': 11, 'door hinges': 11, 'shelves': 11, 'defrost system': 11, 'standard cycles': 11, 'mirror lighting type': 11, 'bolt pattern (number of holes)': 11, 'whistling': 11, 'primary stone gem type': 11, 'seasonal energy efficiency ratio (seer)': 11, 'wireless remote': 11, 'has self-timer': 11, 'switch type ignition switch': 11, 'case type': 11, 'film color': 11, 'number of teeth': 11, 'point style': 10, 'chamber height': 10, 'tire diameter': 10, 'material nylon': 10, 'washer type': 10, 'material bamboo': 10, 'filter class': 10, 'refrigerator fresh food capacity': 10, 'door material type': 10, 'domestic shipping': 10, 'international shipping': 10, 'control console': 10, 'lens coating description': 10, 'tree type': 10, 'container shape': 10, 'seat material type leather': 10, 'number of speeds 3': 10, 'compatible with mattress size': 10, 'mounting type door mount': 10, 'seating capacity 3': 10, 'material borosilicate glass': 10, 'backlight': 10, 'mounting type hanging mount': 10, 'auto part position rear, front': 10, 'pin type': 10, 'product grade performance part': 10, 'focal length description': 10, 'alarm': 10, 'fan count': 10, 'item torque': 10, 'outlet connection type': 9, 'tire type': 9, 'heat output': 9, 'maximum lifting height': 9, 'leg length': 9, 'min. required door width': 9, 'utqg': 9, 'shape l-shaped': 9, 'material polyvinyl chloride (pvc)': 9, 'installation type stick': 9, 'resistance mechanism': 9, 'maximum stride length': 9, 'waist (cm)': 9, 'design': 9, 'band width': 9, 'band size': 9, 'maximum weight recommendation 400 pounds': 9, 'maximum temperature': 9, 'number of drawers 6': 9, 'maximum weight recommendation 300 pounds': 9, 'frame material engineered wood, metal': 9, 'voltage 12 volts': 9, 'number of drawers 3': 9, 'material porcelain': 9, 'low light technology': 9, 'coil voltage': 9, 'auto part position rear': 9, 'measurement accuracy': 9, 'component type': 9, 'surface recommendation furniture': 9, 'subwoofer diameter': 9, 'field of view': 9, 'processor count': 9, 'drain type': 9, 'flow rate': 9, 'merv rating': 9, 'guitar pickup configuration': 8, 'instrument key': 8, 'number of cable strands': 8, 'bulb diameter': 8, 'pitch circle diameter': 8, 'pole material type': 8, 'measurement type':

Define additional entities related to the Amazon dataset and parse all the items

In [9]:
g.add((products_ns["source/1"], RDF.type, PROV.Entity))
g.add((products_ns["source/1"], RDFS.label, Literal("milistu/AMAZON-Products-2023")))
g.add((products_ns["source/1"], SDO.url, URIRef("https://huggingface.co/datasets/milistu/AMAZON-Products-2023")))

g.add((products_ns["online_store/1"], RDF.type, SDO["OnlineStore"]))
g.add((products_ns["online_store/1"], RDFS.label, Literal("Amazon", datatype=XSD.string)))
g.add((products_ns["online_store/1"], SDO.url, URIRef("https://www.amazon.com/")))

for index, row in tqdm(df_amazon[0:50].iterrows()):
    product_uri = products_ns[f'product/{index}']
    offer_uri = products_ns[f'offer/{index}']

    g.add((product_uri, RDF.type, SDO.Product))
    g.add((offer_uri, RDF.type, SDO.Offer))
    g.add((product_uri, SDO.offers, offer_uri))

    g.add((product_uri, products_scheme["hasOnlineStore"], products_ns["online_store/1"]))
    g.add((product_uri, PROV.wasDerivedFrom, products_ns["source/1"]))

    if pd.notna(row['parent_asin']):
        g.add((product_uri, SDO['asin'], Literal(row['parent_asin'], datatype=XSD.string)))

    if pd.notna(row['date_first_available']):
        g.add((offer_uri, SDO.availabilityStarts, Literal(row['date_first_available'], datatype=XSD.date)))

    if pd.notna(row['title']):
        g.add((product_uri, RDFS.label, Literal(row['title'], datatype=XSD.string)))

    if pd.notna(row['description']):
        g.add((product_uri, SDO.description, Literal(row['description'], datatype=XSD.string)))

    if pd.notna(row['main_category']):
        g.add((product_uri, SDO.category, Literal(row['main_category'], datatype=XSD.string)))

    if pd.notna(row['average_rating']):
        g.add((product_uri, SDO.aggregateRating, Literal(row['average_rating'], datatype=XSD.float)))

    if pd.notna(row['price']):
        g.add((offer_uri, SDO.price, Literal(row['price'], datatype=XSD.float)))
        g.add((offer_uri, SDO.priceCurrency, Literal("USD", datatype=XSD.string)))

    if pd.notna(row['features']):
        feature_node = BNode()
        g.add((product_uri, SDO.additionalProperty, feature_node))
        g.add((feature_node, RDF.type, SDO.PropertyValue))
        g.add((feature_node, SDO.name, Literal("Features", datatype=XSD.string)))
        g.add((feature_node, SDO.value, Literal(row['features'], datatype=XSD.string)))


    if not isinstance(row['details'], dict):
        continue

    for (key, value) in row['details'].items():
        added_details = []
        key = key.lower().strip()

        if not (isinstance(key, str) and isinstance(value, str)):
            continue

        if len(key) == 0 or len(value) == 0:
            continue

        # we skip package dimensions because there are no relevant Properties for that, and it is not directly about the product
        if "package dimensions" in key:
            continue

        # we already have date first available, so skip it
        if "date first available" in key:
            continue

        if "dimensions" in key:
            try:
                size, weight = None, None
                split = value.strip().split(";")
                if len(split) == 2:
                    size, weight = split
                else:
                    size = split[0]

                if not weight is None:
                    weight_val, weight_unit = weight.strip().split()
                    weight_node = BNode()
                    g.add((product_uri, SDO.weight, weight_node))
                    g.add((weight_node, RDF.type, SDO.QuantitativeValue))
                    g.add((weight_node, SDO.value, Literal(weight_val, datatype=XSD.float)))
                    g.add((weight_node, SDO.unitText, Literal(weight_unit, datatype=XSD.string)))

                g.add((product_uri, SDO.size, Literal(size, datatype=XSD.string)))
                continue
            except ValueError:
                continue


        matched_prop = find_semantic_match(key, vector_store  )
        if not matched_prop is None:
            # we always consider value type to be string for simplicity,
            # but also it doesn't make sense to create classes like `Country` in the products graph.
            # We have to use property by name, because of prefix mismatch. SDO has namespace with https, but query returns http
            g.add((product_uri, SDO[matched_prop.get('name')], Literal(value, datatype=XSD.string)))
        else:
            # if the detail specification is rare, it is most likely a corrupted string, so we don't add it
            if details_key_counter.get(key, 0) < 5:
                continue
            # if there are no similar properties in schema.org we use sdo:additionalProperty
            spec_node = BNode()
            g.add((product_uri, SDO.additionalProperty, spec_node))
            g.add((spec_node, RDF.type, SDO.PropertyValue))
            g.add((spec_node, SDO.name, Literal(key, datatype=XSD.string)))
            g.add((spec_node, SDO.value, Literal(value, datatype=XSD.string)))

0it [00:00, ?it/s]C:\Users\denve\AppData\Roaming\Python\Python313\site-packages\IPython\core\interactiveshell.py:3701: UserWarning: Code: asin is not defined in namespace SDO
  exec(code_obj, self.user_global_ns, self.user_ns)
50it [00:03, 13.25it/s]

# Enriching the graph with WDC dataset

In [10]:
df_wdc = pd.read_pickle("../data/wdc_products_cleaned.pkl")
# reset the index to align with amazon dataset
df_wdc.set_index(np.arange(len(df_amazon), len(df_amazon) + len(df_wdc), 1, dtype=int), inplace=True)
df_wdc.head()

,category,identifiers,title,description,brand,price,keyValuePairs,url,store name,store url
81359,Tools and Home Improvement,{'/sku': 'gad00192'},"""Bee line Dragway Sign"" ""Drag Racing - Signs f...","""Bee Line Dragway in Arizona - Smell the smoke...",NaN,"""USD"", ""99.95""",NaN,http://garageart.com/products_cat2.asp?Categor...,garageart,garageart.com
81360,Sports and Outdoors,{'/sku': 'underarmourftw1264304001'},"""Under Armour SpeedForm Gemini Men's Team Trai...","""Slide the UA SpeedForm Gemini on & you immedi...","""Baseball Monkey""@en","""USD""@en, ""129.99""@en",NaN,https://www.baseballmonkey.com/homerun-footwea...,baseballmonkey,www.baseballmonkey.com
81361,Other Electronics,"{'/gtin8': '43233205', '/mpn': 'cese1gscu'}","""Sophos Central Endpoint Standard - competitiv...","""Sophos Cloud is the only integrated security ...",NaN,"""$"", ""22.70""",NaN,https://www.cdw.com/shop/products/Sophos-Cloud...,cdw,www.cdw.com
81362,Computers and Accessories,{'/mpn': 'hardkernelodroidxu4'},"""Odroid XU4 - 8 Core Odroid computer (inc PSU)...",networking especially with faster booting USB ...,"""Hard Kernel""@en","""91.19€""@en, ""EUR""@en",NaN,https://lilliputdirect.com/index.php?_route_=o...,lilliputdirect,lilliputdirect.com
81363,Sports and Outdoors,{'/sku': 'rwlbhr16h2j'},"""Rawlings Velo Two-Tone Home Junior Batting He...","""With its eye-catching finish and ultra-cushio...","""Baseball Monkey""@en","""USD""@en, ""42.99""@en",NaN,https://www.baseballmonkey.com/equipment/homer...,baseballmonkey,www.baseballmonkey.com

In [11]:
keyValuePairs_key_counter = Counter()
for details in df_wdc['keyValuePairs']:
    if pd.isna(details):
        continue

    for key in details.keys():
        keyValuePairs_key_counter.update([key.lower().strip()])

print(keyValuePairs_key_counter)

Counter({'category': 1342, 'part number': 1214, 'sub-category': 1210, 'generation': 1210, 'products id': 986, '': 863, 'capacity': 620, 'manufacturer': 539, 'spindle speed': 458, 'form factor': 403, 'interface type': 395, 'data transfer rate': 365, 'type': 343, 'interface': 328, 'pre-failure warranty': 242, 'enclosure': 227, 'product id': 224, 'hot swap tray': 211, 'product type': 210, 'seek time': 201, 'drive dimensions': 192, 'pax-code': 188, 'item code': 186, 'version': 184, 'processor qty': 180, 'ports': 179, 'clock speed': 176, 'processor type': 175, 'processor core': 175, 'official release date': 175, 'genre': 173, 'hotswap': 172, 'processor socket': 172, 'l2 cache': 165, 'thermal design power': 163, '64-bit processing': 161, 'process technology': 146, 'catalog no.': 137, 'rotational speed': 137, 'ad id': 128, 'posted': 128, 'expiry': 128, 'status': 128, 'external data transfer': 123, 'details': 106, 'weight': 100, 'l3 cache': 95, 'enclosure type': 92, 'bus speed': 92, 'tape type': 89, 'renewed': 86, 'compressed capacity': 86, 'native capacity': 84, 'prezzo articolo': 81, 'condizione': 81, 'codice prodotto': 81, 'disponibilità': 81, 'spedizione': 81, 'disponibile da': 81, 'device type': 80, 'connector': 79, 'original name': 71, 'average seek time': 69, 'platform': 67, 'height': 67, 'technology': 66, 'pins': 65, 'brand': 64, 'players': 58, 'data storage device type': 58, 'speed': 56, 'scsi signaling type': 56, 'hard drive device type': 55, 'application': 52, 'quickpath interconnect': 49, 'language': 47, 'average latency': 47, 'dimensions (hxwxd)': 45, 'hypertransport speed': 44, 'l1 cache': 44, 'package qty': 41, 'native data transfer rate': 40, 'external data transfer rate': 40, 'actual wattage': 40, 'subtitles': 37, 'hot swap': 37, 'base type': 37, 'website': 36, 'data transfer rate - compressed': 36, 'voltage': 36, 'model': 34, 'compatibility': 34, 'useful life hours': 34, 'length (inch)': 34, 'dimensions (wxdxh)': 33, 'drive capacity': 33, 'bulb shape': 33, 'product code': 31, 'cache': 30, 'auto switching': 30, 'cooling': 30, 'fan': 30, 'server model': 29, 'hp serial number': 29, 'hp logo': 29, 'guaranteed genuine hp': 29, 'audio': 29, 'additional information': 29, 'size': 28, 'processor': 27, 'power provided': 27, 'diameter (inch)': 27, 'interface (detailed)': 26, 'pfc': 26, 'screen format': 26, 'color rendering index': 26, 'limited warranty': 25, 'compression': 25, 'running time': 25, 'color temperature (kelvin)': 25, 'access time': 25, 'buffer size': 24, 'input voltage': 23, 'starring': 22, 'brands': 22, 'small form factor': 21, 'bytes/sector': 21, 'director': 21, 'year': 21, 'wattage': 21, 'hot pluggable': 21, 'video format': 21, 'lumen output': 21, 'native command queuing': 20, 'processor technology': 20, 'controller interface type': 20, 'cache memory': 20, 'installed memory': 19, 'wax type': 18, 'memory technology': 18, 'redundant': 18, 'additional info': 17, 'höhe': 16, 'energieeffizienzklasse leuchten': 16, 'operating temperature': 16, 'power': 16, 'mtbf': 15, 'color': 15, 'length': 15, 'raid level': 15, 'processor speed': 15, 'raid support': 14, 'storage capacity': 14, 'amount per serving': 14, 'burn position': 14, 'breite': 14, 'spare number': 13, 'candle colour': 13, 'input voltage range': 13, 'supported devices': 13, 'minimum qty': 13, 'networking': 13, 'controller type': 13, 'leuchtmittel im lieferumfang': 13, 'lichtverteilung': 13, 'spannung': 13, 'item #': 12, 'msrp': 12, 'single track': 12, 'full-stroke': 12, 'logical blocks': 12, 'fragrance': 12, 'filament type': 12, 'cache size': 12, 'maximum number of processors': 12, 'lichtfarbtemperatur (kelvin)': 12, 'lichtstrom (lm)': 12, 'data link protocol': 11, 'dimmbar': 11, 'material/oberfläche': 11, 'dimensions (wxhxd)': 11, 'width (inch)': 11, 'memory': 11, 'hard drive': 11, 'storage controller': 11, 'cabling type': 11, 'included network card': 11, 'operating system': 11, 'lichtsteuerung': 11, 'schutzart': 11, 'product measures': 11, 'bus clock': 10, 'ram technology': 10, 'large form factor': 10, 'format': 10, 'frequency required': 10, 'memory speed': 10, 'max storage devices qty': 10, 'average': 10, 'länge': 10, 'dimensions': 10, 'material': 10, 'system chipset': 10, 'dimmer inklusive': 10, 'designer': 10, 'artist': 9, 'sonstige maße': 9, 'host interface': 9, 'dimensions (hxw)': 9, 'memory socket': 9, 'ecc / registered': 8, 'procesor type': 8, 'connector type': 8, 'transfer rate synchronous (maximum)': 8, 'warranty': 8, 'beam degrees': 8, 'channel qty': 8, 'network controller': 8, 'ram': 8, 'maximum system memory': 8, 'optical drive': 8, 'farbwiedergabeindex cri': 8, 'system type': 7, 'width': 7, 'durchmesser': 7, 'jahr': 7, 'thermal specification': 7, 'equivalent wattage': 7, 'dimmable': 7, 'manufacturers warranty': 7, 'ram (maximum)': 7, 'scsi interface': 7, 'recommended machine type': 7, 'bus type': 7, 'internal storage': 7, 'processor capacity': 7, 'memory type': 7, 'storage type': 7, 'removable media bays': 7, 'remote management': 7, 'redundant power supply': 7, 'tiefe': 7, 'cache per processor': 7, 'graphics controller': 7, 'height (inch)': 7, 'standard memory': 7, 'prüfzeichen': 7, 'number of memory slots': 7, 'features': 6, 'sku': 6, 'interfaces/ports': 6, 'media type': 6, 'burn time': 6, 'storage capacity (max.)': 6, 'minimum focusing distance': 6, 'manufacturers notes': 6, 'channels': 6, 'farbe': 6, 'gewicht': 6, 'focal length': 6, 'filter size': 6, 'groups': 6, 'elements': 6, 'ram (installed)': 6, 'networking protocol': 6, 'hight': 6, 'model number': 6, 'movement': 6, 'target use': 6, 'hard drive capacity': 6, 'connectivity technology': 6, 'hdd form factor': 6, 'drive support': 6, 'rack height': 6, 'redundant fans': 6, 'ports qty': 6, 'dimensions (wxh)': 6, 'diskette drive': 6, 'optical storage': 6, 'max. data transfer rate': 6, 'case quantity': 5, 'maximum ram': 5, 'networking type': 5, 'data transfer rate (max.)': 5, 'installed l2 cache memory': 5, 'backward compatability': 5, 'installed devices / modules qty': 5, 'storage controller type': 5, 'art der fliese': 5, 'oberfläche': 5, 'kante': 5, 'sortierung': 5, 'fliesenstärke': 5, 'verwendung': 5, 'frostsicher': 5, 'lens mount': 5, 'diagonal angle of view': 5, 'maximum diameter': 5, 'lens format': 5, 'cache memory (installed)': 5, 'series': 5, 'crystal': 5, '# of internal connectors': 5, '# of external connectors': 5, 'maximum supported devices': 5, 'chassis form factor': 5, 'max memory': 5, 'advanced memory protection': 5, 'included drives': 5, 'condition': 5, 'drive interface standard': 5, 'total storage capacity': 5, 'dimensions (wxd)': 5, 'number of pci express x8 slots': 5, 'processors qty': 4, 'installed ram': 4, 'disk size': 4, 'bytes/sec': 4, 'uk saver': 4, 'next day delivery': 4, 'next evening delivery': 4, 'europe delivery': 4, 'worldwide shipping': 4, 'contact us+44 (0) 207 281 9671': 4, '500 - 999': 4, 'additional certifications': 4, 'interface(s) required': 4, 'stück je karton': 4, 'aperture range': 4, 'case material': 4, 'dial color': 4, 'band material': 4, 'water resistant': 4, 'transfer rate synchronous (max)': 4, 'processor class': 4, 'chassis style': 4, 'upgrade type': 4, 'gender': 4, 'number of pci express slots': 4, '1-99': 4, '100+': 4, 'remote management protocol': 4, 'candle power (mbcp/cbcp)': 4, 'mbcp/cbcp': 4, 'scalability': 4, 'drive controllers': 4, 'firmware': 4, 'sun original': 4, 'removable media capacity': 4, 'power output': 4, 'frequency': 4, 'kabellänge': 4, 'floppy drive': 4, 'vorschaltgerät inklusive': 4, 'manufacturer id': 3, 'item weight': 3, 'item package dimensions (l x w x h)': 3, 'peso': 3, 'notes': 3, 'cas latency': 3, 'number of modules': 3, 'package quantity': 3, 'quantity': 3, '250 - 499': 3, '1000 - 2499': 3, 'cable/connector type': 3, 'packaged quantity': 3, 'hard drive interface': 3, 'net weight': 3, 'abrieb klasse': 3, 'rutschhemmung': 3, 'transfer rate': 3, 'ansi code': 3, 'transfer speed': 3, 'input voltage type': 3, 'product dimensions (wxhxd)': 3, 'native capcity': 3, 'construction': 3, 'dimensions (w x d x h)': 3, '1-9': 3, '10+': 3, 'pages': 3, 'number of pci slots': 3, 'clasp type': 3, 'dlc listed': 3, 'tipo': 3, 'total value': 3, 'your cost': 3, 'you save': 3, 'rank': 3, 'board/module type': 3, 'maximum transfer rate': 3, 'fibre channel element': 3, 'port speed': 3, 'ports per chassis': 3, 'operating power': 3, 'physical dimensions (wxhxd)': 3, 'contrast ratio': 3, 'mounting': 3, 'localization': 3, 'output power': 3, 'upc code': 3, 'availability': 3, 'ships free?': 3, 'raid controller': 3, 'mittlere lebensdauer': 3, 'upc': 3, 'interface compatibility': 3, 'duplex mode': 3, 'networking connectors': 3, 'bus clock rate': 3, 'bus clock bits': 3, 'power management': 3, 'power requirements': 3, 'colour': 3, 'processor main features': 3, 'monitor': 3, 'compatability': 3, 'blade material': 2, 'blade type': 2, 'folding action': 2, 'handle construction': 2, 'blade length': 2, 'handle length': 2, 'overall length': 2, 'network architecture': 2, 'finish': 2, 'action': 2, 'caliber': 2, 'barrel length': 2, 'safety': 2, 'grips': 2, 'sights': 2, 'growing zones': 2, 'mature height': 2, 'mature width': 2, 'sunlight': 2, 'spacing': 2, 'botanical': 2, 'cannot ship to': 2, 'order total': 2, '$0 - $9.99': 2, '$10 - $19.99': 2, '$20 - $29.99': 2, '$30 - $39.99': 2, '$40 - $59.99': 2, '$60 - $78.99': 2, 'uk orders under £250': 2, 'uk orders over £250': 2, 'international jewellery deliveries': 2, 'international sculpture deliveries': 2, 'click & collect (jewellery only)': 2, 'memory size': 2, 'single track seek time': 2, 'full stroke seek time': 2, 'server type': 2, 'power consumption (max.)': 2, 'retail': 2, 'free shipping, no tax': 2, '5000+': 2, 'bytes per sector': 2, 'interface/ports': 2, 'transfer rate (max.)': 2, 'maximum number of drives': 2, 'maximum number of cartridges': 2, 'maximum temperature range': 2, 'magnification': 2, 'cells': 2, 'input connector(s)': 2, 'compressed capcity': 2, 'brennwert': 2, 'fett': 2, 'kohlenhydrate': 2, 'eiweiß': 2, 'salz': 2, 'dosis': 2, 'video ram (installed)': 2, 'video card': 2, 'number of free expansion bays': 2, 'power device': 2, 'operating temperature range': 2, 'case diameter': 2, 'connector(s) (other side)': 2, 'level': 2, 'actual weight': 2, 'metal stamp': 2, 'metal': 2, 'collapsed size': 2, 'collapsible': 2, 'colour temperature': 2, 'colour temperature (reversed)': 2, 'reversible': 2, 'shape': 2, 'buffer': 2, 'diamonds': 2, 'drive interface': 2, 'serving size': 2, 'ref': 2, 'itemno.': 2, 'made in': 2, 'released': 2, 'compressed data transfer rate': 2, 'water resistance': 2, 'maximum capacity': 2, 'networking data': 2, 'rain support': 2, 'maximum number of devices supported': 2, 'scsi signaling (differential)': 2, 'mhz': 2, 'primary diameter': 2, 'focal ratio': 2, 'focuser': 2, 'mount': 2, 'telescope length': 2, 'telescope weight, optical tube/assembled': 2, 'internal drive transfer': 2, 'tamanho dose': 2, 'cd-rom read speed': 2, '2500+': 2, 'storage controller raid level': 2, 'kvm users qty': 2, 'shred size': 2, 'feed opening': 2, 'shipping weight': 2, 'security level': 2, 'recording standard': 2, 'grossissement': 2, 'diamètre': 2, 'etanchéité': 2, 'poids en gramme': 2, 'caractéristique': 2, 'diagonal size': 2, 'viewable size': 2, 'resolution': 2, 'refresh rate at max resolution': 2, '450': 2, 'pitch': 2, 'horizontal viewing angle': 2, 'vertical viewing angle': 2, 'monitor color': 2, 'included devices': 2, 'produktbeschreibung': 2, 'gerã¤tetyp': 2, 'ballast start type': 2, 'modelo': 2, 'cor': 2, 'altura do produto': 2, 'largura do produto': 2, 'profundidade do produto': 2, 'price': 2, 'schirm': 2, 'interface (bus) type': 2, 'network / transport protocol': 2, 'cable length': 2, 'misura della dose': 2, 'ausladung': 2, 'interior size': 2, 'exterior size': 2, 'carrying options': 2, 'weatherproof': 2, 'closure type': 2, 'retail number': 2, 'awards': 2, 'kopf': 2, 'alternate part number': 2, 'fit length': 2, 'fit width': 2, 'built-in devices': 2, 'standard data-rate': 2, 'led indicators': 2, 'storage controller raid': 2, 'dose': 2, 'fuß': 2, 'memory kit': 2, 'processort type': 2, 'small': 2, 'medium': 2, 'large': 2, 'x-large': 2, 'xx-large': 2, 'compatible slots': 2, 'signal processing': 2, 'dimensions (dxh)': 2, 'chipset': 2, 'video output interface': 2, 'outdoor use': 2, 'number of externally accessible 5.25 bay': 2, 'manufacturer warranty': 2, 'networking network adapter': 2, 'chipkill': 2, 'graphics controller pci': 2, 'list price': 1, 'our price': 1, 'ships from': 1, 'length and hook options': 1, '01.': 1, '02.': 1, '03.': 1, '04.': 1, '05.': 1, 'manufacturer part#': 1, 'altura': 1, 'anchura': 1, 'largo': 1, 'capacidad': 1, 'composición': 1, 'voltaje': 1, 'marca': 1, 'per dose': 1, 'platform pc': 1, 'over $79': 1, 'compressd capacity': 1, 'memory standard': 1, 'leuchtenkörper': 1, 'réf.': 1, '27277': 1, '27276': 1, 'connectors': 1, 'connector details': 1, '2500 - 4999': 1, '1000 - 2999': 1, '3000+': 1, 'number of installed drives': 1, 'type of prism': 1, 'magnification range': 1, 'front lens diameter': 1, 'twilight factor': 1, 'field of view 1000 yards': 1, 'fogproof / waterproof': 1, 'rolex model': 1, 'bezel type': 1, 'max. number of storage devices': 1, 'output voltage': 1, 'dimension': 1, 'fan size': 1, 'adjustable angles': 1, 'noise level': 1, 'power consumption': 1, 'fan speed': 1, 'davon': 1, 'kalorien proteine kohlenhydrate fett': 1, 'chassis form': 1, 'controller raid level': 1, 'intrface': 1, 'power supply': 1, 'por cada toma': 1, 'connector(s)': 1, 'type of switch': 1, 'max voltage': 1, 'min voltage': 1, 'speeds supported-network': 1, 'age (years)': 1, 'data integrity check': 1, 'tamanho por dose': 1, 'extracto de valeriana': 1, 'network adaptor': 1, 'platform support': 1, 'energi': 1, 'protein': 1, 'kulhydrat': 1, '- heraf sukkerarter': 1, 'fedt': 1, '- heraf mættede fedtsyrer': 1, 'kostfibre': 1, 'natrium': 1, 'open size (from handle to opposite side)': 1, 'screen size': 1, 'mount diameter': 1, '50 - 99': 1, '100 - 199': 1, '200 - 999': 1, '1000 - 4999': 1, 'case': 1, 'limited edition': 1, 'dial': 1, 'functions': 1, 'data rate': 1, 'cable distance': 1, 'tamanho servi?o': 1, 'vitamina c': 1, 'tamanho toma': 1, 'calorias proteínas carboidratos gorduras l-leucina l-isoleucina l-valina': 1, 'fat (from fish oil)  eicosapentaenoic acid (epa 18%)   docosahexanoic acid (12% dha)   other omega-3 fatty acids (10%)  vitamin e': 1, 'taille par dose': 1, 'extrait de pépin de raisin': 1, 'crown': 1, 'native storage capacity': 1, 'tamaño': 1, 'model no.': 1, 'case size': 1, 'capacity compressed': 1, 'tape length': 1, 'package contents': 1, 'drive count': 1, 'product dimensions': 1, 'operating temp': 1, 'raid': 1, 'protocol supported': 1, '603.066.39': 1, '703.066.86': 1, 'pendellänge': 1, 'extrato de mango africano irvingia gabonensis igob131': 1, '*note': 1, '100 - 299': 1, '300 - 499': 1, 'cd/dvd rom': 1, 'number of processors installed': 1, 'number processors supported': 1, 'un service': 1, 'acide alpha lipoïque': 1, 'rorational speed': 1, 'manufacture': 1, 'sheet capacity': 1, 'shred speed': 1, 'approximate dimensions (wxdxh)': 1, 'approximate weight': 1, 'processor clock speed': 1, 'cache standard, secondary': 1, 'ram standard': 1, 'ram type': 1, 'number of processors included': 1, 'raid controller included': 1, 'raid notes': 1, 'product quantity': 1, 'vitamin c rose hips': 1, 'antibuée': 1, 'server scalability': 1, 'operating voltage': 1, 'data buffer': 1, 'eingangsspannung': 1, 'leistungskapazitã¤t': 1, 'entwickelt fã¼r': 1, '158': 1, '130': 1, '106': 1, '120': 1, 'network ports quantity': 1, 'capacity (box)': 1, 'shipping weight (kg)': 1, 'shipping weight (lb)': 1, 'notebook acer 15,6"" es1-572-3562 i3-6006u 4gb 1tb w10 preto': 1, 'produto': 1, 'tela': 1, 'memória': 1, 'processador': 1, 'disco rígido': 1, 'sistema operacional': 1, 'áudio': 1, 'unidade ótica': 1, 'leitor de cartões': 1, 'teclado': 1, 'bluetooth': 1, 'webcam': 1, 'tipo de bateria': 1, "diamètre de l'objectif": 1, 'diamètre de la pupille de sortie': 1, 'indice crépusculaire': 1, 'champ de vision à 1000 m': 1, "angle de vision de l'objectif": 1, 'distance minimum de mise au point': 1, "plage d'ajustement dioptrique": 1, 'écart inter-pupillaire': 1, 'retrait oculaire': 1, 'hd fl achromate': 1, 'système de prismes': 1, 'traitement externe des lentilles': 1, "étanche à l'immersion": 1, "injection d'azote": 1, 'plage thermique de fonctionnement': 1, 'hauteur': 1, 'largeur pour un écart oculaire de 65mm': 1, 'poids': 1, 'digital inputs': 1, 'lens shift': 1, 'standard lens focus': 1, 'throw distance (ft.)': 1, 'native resolution': 1, 'aspect ratio': 1, '16': 1, 'lumens': 1, '1,000,000': 1, 'form factor height': 1, 'form factor width': 1, 'tape format': 1, 'motor': 1, 'shredder speed': 1, 'shred capacity': 1, 'auto on / off': 1, 'auto reverse': 1, 'bag full auto off': 1, 'waste volume': 1, 'cutting block warranty': 1, 'accepts paper clips / staples': 1, 'tamanho': 1, 'max transfer distance': 1, 'output power (va)': 1, 'output power (w)': 1, 'max backup time with full load': 1, 'total number of outputs': 1, 'outlet connectors': 1, 'recharge time': 1, 'surge suppression': 1, 'automatic shutdown': 1, 'audible alarm': 1, 'motorisation': 1, 'type de monture': 1, 'charge utile': 1, 'poids du trépied': 1, 'poids de la monture': 1, 'poids total de la monture': 1, 'contrepoids': 1, 'alimentation': 1, "embase queue d'aronde": 1, 'l-glutammina * la percentuale della dose giornaliera è basata su una dieta da 2000 calorie † dose giornaliera non stabilita.': 1, 'artikel nr.': 1, 'hersteller': 1, 'typ': 1, 'hergestellt in': 1, 'zustand': 1, 'veröffentlicht': 1, 'package qty.': 1, 'memory protection': 1, 'max drive bays': 1, 'rack hight': 1, 'kalzium lycopen (aus tomaten) tomatenpulver': 1, 'auxiliary network ports': 1, '4kb random read': 1, '4kb random write': 1, 'apn': 1, 'dimensions (lxwxh)': 1, 'arm': 1, 'aufbaudose': 1, 'total processor supported': 1, 'maximum memory': 1, 'optical drive speed': 1, 'expansion bays': 1, 'case style': 1, 'hot-swap': 1, "rogan's best fit guide": 1, 'heel drop': 1, 'maximum supported memory': 1, 'wieght': 1, 'process socket': 1, 'qty': 1, 'fibre psillium husks': 1, 'drive tray': 1, 'sata storage device type': 1, 'sata pin': 1, 'native capacity (gb)': 1, 'compressed capacity (gb)': 1, 'total storage capacity (native)': 1, 'total storage capacity (compressed)': 1, 'media': 1, 'recording format': 1, 'backward write': 1, 'backward read': 1, 'backward compatibility': 1, 'borrago officinalis omega 6 vitamin e': 1, 'management': 1, 'configuration type': 1, 'blooms': 1, '$80 - $98.99': 1, 'over $99': 1, 'managed device': 1, 'fibre channel port speed': 1, 'switch fabric capacity': 1, 'conductors': 1, 'cable type': 1, 'cond. type': 1, 'wire type': 1, 'packaging': 1, 'certifications': 1, 'jacket color': 1, 'lead time': 1, 'cable marking': 1, 'surface type': 1, 'total qty': 1, 'max operating temerature': 1, 'min operating temperature': 1, 'raiz de ginseng de coréia': 1, 'tamaño por toma': 1, 'sulfato de glucosamina sulfato de condroitina': 1, 'erdstück': 1, 'cabinet form factor': 1, 'power type': 1, 'diffusor': 1, 'city': 1, 'state': 1, 'aluminium bronzefarben brüniert, diffusor': 1, 'formatted capacity': 1, 'compliant standards': 1, 'track-to-track seek time': 1, 'lining': 1, 'outsole construction': 1, 'upper material': 1, 'heel height': 1, 'analysis': 1, 'application rate': 1, 'coverage': 1, 'granule/liquid': 1, 'granule size (mm)': 1, 'longevity': 1, 'pack size': 1, 'processor(s)': 1, 'models': 1, 'raid levels': 1, 'interfaces': 1, 'standard data rate': 1, '3" (76.2mm)': 1, '2-1/2" (64mm)': 1, '300lbs (140kg)': 1, '0.8 lbs (0.36kg)': 1, 'load rating': 1, 'output connector(s)': 1, 'battery': 1, 'run time (up to)': 1, 'aluminium veredelt, fuß': 1, 'manageable': 1, 'nährwerte/100g¹': 1, '- davon gesättigte fettsäuren': 1, '- davon omega-3-fettsäuren': 1, '- davon zucker': 1, '184': 1, '141': 1, '116': 1, '131': 1, '25': 1, '150': 1,

In [12]:
identifiers_counter = Counter()
for details in df_wdc['identifiers']:
    if pd.isna(details):
        continue

    for key in details.keys():
        identifiers_counter.update([key])

print(identifiers_counter)

Counter({'/sku': 14446, '/mpn': 4983, '/gtin8': 1774, '/gtin13': 1293, '/productID': 666, '/identifier': 74, '/gtin12': 55, '/gtin14': 31})

In [13]:
# We manually create mapping for identifiers and relevant schema properties, to avoid running semantics search more than necessary
identifiers_mapping = {
    "/sku": SDO.sku,
    "/mpn": SDO.mpn,
    "/gtin8": SDO.gtin8,
    "/gtin12": SDO.gtin12,
    "/gtin13": SDO.gtin13,
    "/gtin14": SDO.gtin14,
    "/productID": SDO.productID,
    "/identifier": SDO.identifier,
}

In [14]:
def extract_price(input_string):
    # Mapping for common symbols to ISO 4217 codes
    symbol_to_iso = {
        "$": "USD",
        "€": "EUR",
        "£": "GBP",
        "¥": "JPY",
        "₹": "INR"
    }

    # A matching pattern for price, considering commas as delimiters and dot as fraction separator
    price_pattern = r'(?:\d{1,3}(?:,\d{3})*|\d+)(?:\.\d+)?'

    # Matches 3-letter uppercase codes or common symbols
    currency_pattern = r'[A-Z]{3}|[\$\€\£\¥]'

    # Extract price and currency
    price_match = re.search(price_pattern, input_string)
    currency_match = re.search(currency_pattern, input_string)

    if price_match is None:
        return None, None

    # Clean price value
    price_val = price_match.group(0) if price_match else None
    if price_val:
        price_val = price_val.replace(',', '')

    if currency_match is None:
        return price_val, currency_match

    # Map to ISO standard code
    raw_currency = currency_match.group(0) if currency_match else None
    iso_currency = symbol_to_iso.get(raw_currency, raw_currency)

    return float(price_val), iso_currency

In [15]:
g.add((products_ns["source/2"], RDF.type, PROV.Entity))
g.add((products_ns["source/2"], RDFS.label, Literal("Web Data Commons, Product Data Corpus (English)")))
g.add((products_ns["source/2"], SDO.url, URIRef("http://webdatacommons.org/largescaleproductcorpus/v2/index.html")))

stores_unique = set()
store_id = 1 # we start from 2, because 1 is already Amazon
for index, row in tqdm(df_wdc[0:50].iterrows()):
    store_id += 1
    product_uri = products_ns[f'product/{index}']
    offer_uri = products_ns[f'offer/{index}']
    store_uri = products_ns[f"online_store/{store_id}"]

    g.add((product_uri, RDF.type, SDO.Product))
    g.add((offer_uri, RDF.type, SDO.Offer))
    g.add((product_uri, SDO.offers, offer_uri))

    g.add((product_uri, PROV.wasDerivedFrom, products_ns["source/1"]))

    # add store if it doesn't yet exist in the graph
    if row["store name"] not in stores_unique:
        g.add((store_uri, RDF.type, SDO["OnlineStore"]))
        g.add((store_uri, RDFS.label, Literal(row["store name"], datatype=XSD.string)))
        g.add((store_uri, SDO.url, URIRef(row["store url"])))
        stores_unique.add(row["store name"])

    g.add((product_uri, products_scheme["fromOnlineStore"], store_uri))
    g.add((product_uri, SDO.url, URIRef(row['url'])))

    for identifier, id_value in row['identifiers'].items():
        g.add((product_uri, identifiers_mapping[identifier], Literal(id_value, datatype=XSD.string)))

    if pd.notna(row['title']):
        g.add((product_uri, RDFS.label, Literal(row['title'], datatype=XSD.string)))

    if pd.notna(row['description']):
        g.add((product_uri, SDO.description, Literal(row['description'], datatype=XSD.string)))

    if pd.notna(row['category']):
        g.add((product_uri, SDO.category, Literal(row['category'], datatype=XSD.string)))

    if pd.notna(row['brand']):
        g.add((product_uri, SDO.brand, Literal(row['brand'], datatype=XSD.string)))


    if pd.notna(row['price']):
        price, currency = extract_price(row["price"])

        if price is None:
            continue
        g.add((offer_uri, SDO.price, Literal(price, datatype=XSD.float)))

        if currency is None:
            continue
        g.add((offer_uri, SDO.priceCurrency, Literal(currency, datatype=XSD.string)))


    if not isinstance(row['keyValuePairs'], dict):
        continue

    for (key, value) in row['keyValuePairs'].items():
        added_details = []
        key = key.lower().strip()

        if not (isinstance(key, str) and isinstance(value, str)):
            continue

        if len(key) == 0 or len(value) == 0:
            continue

        if "dimensions" in key:
            try:
                size, weight = None, None
                split = value.strip().split(";")
                if len(split) == 2:
                    size, weight = split
                else:
                    size = split[0]

                if weight is not None:
                    weight_val, weight_unit = weight.strip().split()
                    weight_node = BNode()
                    g.add((product_uri, SDO.weight, weight_node))
                    g.add((weight_node, RDF.type, SDO.QuantitativeValue))
                    g.add((weight_node, SDO.value, Literal(weight_val, datatype=XSD.float)))
                    g.add((weight_node, SDO.unitText, Literal(weight_unit, datatype=XSD.string)))

                g.add((product_uri, SDO.size, Literal(size, datatype=XSD.string)))
                continue
            except ValueError:
                continue

        matched_prop = find_semantic_match(key, vector_store)
        if not matched_prop is None:
            # we always consider value type to be string for simplicity,
            # but also it doesn't make sense to create classes like `Country` in the products graph.
            g.add((product_uri, SDO[matched_prop.get('name')], Literal(value, datatype=XSD.string)))
        else:
            # if the detail specification is rare, it is most likely a corrupted string, so we don't add it
            if details_key_counter.get(key, 0) < 5:
                continue
            # if there are no similar properties in schema.org we use sdo:additionalProperty
            spec_node = BNode()
            g.add((product_uri, SDO.additionalProperty, spec_node))
            g.add((spec_node, RDF.type, SDO.PropertyValue))
            g.add((spec_node, SDO.name, Literal(key, datatype=XSD.string)))
            g.add((spec_node, SDO.value, Literal(value, datatype=XSD.string)))

50it [00:00, 69.47it/s]

In [16]:
g.serialize(destination="../data/graph.ttl", format='ttl')

---
# Validating Graph with SHACL
We can use `pyshacl` library to validated out graph against the shape file

In [17]:
from pyshacl import validate

shape_g = Graph().parse("SHACL.ttl")
conforms, results_graph, results_text = validate(data_graph=g, shacl_graph=shape_g)
print(results_text)

Validation Report
Conforms: False
Results (29):
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/10>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/10>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/11>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/11>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/12>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/12>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/14>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/14>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/17>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/17>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/18>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/18>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/19>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/19>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/1>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/1>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/20>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/20>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/21>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/21>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/25>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/25>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/2>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/2>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/30>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/30>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/31>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/31>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/32>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/32>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/33>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/33>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/35>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/35>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/36>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/36>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/38>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/38>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/39>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/39>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/3>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/3>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/43>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/43>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/44>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/44>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/46>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/46>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/4>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/4>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/5>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/5>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/online_store/9>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/online_store/9>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/source/1>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/source/1>->rdfs:url
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:minCount Literal("1", datatype=xsd:integer) ; sh:nodeKind sh:IRI ; sh:path rdfs:url ]
	Focus Node: <http://products-kg.org/source/2>
	Result Path: rdfs:url
	Message: Less than 1 values on <http://products-kg.org/source/2>->rdfs:url